const PHRASES = {
    'Der': {
        'Mann': 1,
        'Brüder': 1,
        'Sohn': 1,
        'Student': 1,
        'Job': 1,
        'Kugelschreiber': 1,
        'Großvater': 1,
        'Schwiegervater': 1,
        'Apfel': 1,
        'Tisch': 1,
    },
    'Die': {
        'Frau': 1,
        'Tochter': 1,
        'Studentin': 1,
        'Arbeit': 1,
        'Brille': 1,
        'Großmutter': 1,
        'Schwiegermutter': 1,
        'Banane': 1,
        'Tasche': 1,
        'Anzeige': 1,
    },
    'Das': {
        'Mädchen': 1,
        'Tier': 1,
        'Auto': 1,
        'Papier': 1,
        'Essen': 1,
        'Kind': 1,
        'Enkelkind': 1,
        'Fotoapparat': 1,
        'Wasser': 1,
        'Haus': 1,
    },
};